Rush 01/intranet/src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\UserRole;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'This email is already registered.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $first_name = null;

    #[ORM\Column(length: 60)]
    private ?string $last_name = null;

    #[ORM\Column(length: 100, unique: true)]
    private ?string $email = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $created = null;

    #[ORM\Column(enumType: UserRole::class)]
    private ?UserRole $role = null;

    #[ORM\Column(length: 64, nullable: true, unique: true)]
    private ?string $confirmationToken = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isActive = false;

    #[ORM\ManyToMany(targetEntity: Event::class, mappedBy: 'users')]
    private Collection $events;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $image = null;

    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private int $experience = 0;

    #[ORM\Column(type: 'integer', nullable: false)]
    private int $evalPoints;

    #[ORM\OneToMany(targetEntity: EvalSlot::class, mappedBy: 'userId', orphanRemoval: true)]
    private Collection $evalSlots;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserProject::class, orphanRemoval: true)]
    private Collection $userProjects;

    #[ORM\Column(type: 'json', nullable: true)]
    private ?array $notifications = [];

    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private int $unreadNotificationsCount = 0;

    #[ORM\Column(type: 'integer', options: ['default' => 1])]
    private int $level = 1;

    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->experience = 0;
        $this->evalPoints = 5;
        $this->evalSlots = new ArrayCollection();
        $this->userProjects = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;
        return $this;
    }

    public function getEvalPoints(): int
    {
        return $this->evalPoints;
    }

    public function setEvalPoints(int $evalPoints): static
    {
        $this->evalPoints = $evalPoints;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): static
    {
        $this->password = $password;
        return $this;
    }

    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    public function setCreated(\DateTime $created): static
    {
        $this->created = $created;
        return $this;
    }

    public function getRole(): ?UserRole
    {
        return $this->role;
    }

    public function setRole(UserRole $role): static
    {
        $this->role = $role;
        return $this;
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmationToken;
    }

    public function setConfirmationToken(?string $confirmationToken): static
    {
        $this->confirmationToken = $confirmationToken;
        return $this;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): static
    {
        $this->isActive = $isActive;
        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->isActive;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        if (!$this->role) {
            return [];
        }

        return ['ROLE_' . strtoupper($this->role->value)];
    }

    public function eraseCredentials(): void
    {
        // Clear temporary sensitive data if any
    }

    /**
     * @return Collection<int, Event>
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): static
    {
        if (!$this->events->contains($event)) {
            $this->events->add($event);
            $event->addUser($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): static
    {
        if ($this->events->removeElement($event)) {
            $event->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, UserProject>
     */
    public function getUserProjects(): Collection
    {
        return $this->userProjects;
    }

    public function addUserProject(UserProject $userProject): static
    {
        if (!$this->userProjects->contains($userProject)) {
            $this->userProjects->add($userProject);
            $userProject->setUser($this);
        }

        return $this;
    }

    public function removeUserProject(UserProject $userProject): static
    {
        if ($this->userProjects->removeElement($userProject)) {
            if ($userProject->getUser() === $this) {
                $userProject->setUser(null);
            }
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;
        return $this;
    }

    public function getExperience(): int
    {
        return $this->experience;
    }

    public function setExperience(int $experience): static
    {
        $this->experience = $experience;
        return $this;
    }

    public function addExperience(int $xp): static
    {
        $this->experience += $xp;
        return $this;
    }

    /**
     * @return Collection<int, EvalSlot>
     */
    public function getEvalSlots(): Collection
    {
        return $this->evalSlots;
    }

    public function addEvalSlot(EvalSlot $evalSlot): static
    {
        if (!$this->evalSlots->contains($evalSlot)) {
            $this->evalSlots->add($evalSlot);
            $evalSlot->setUserId($this);
        }

        return $this;
    }

    public function removeEvalSlot(EvalSlot $evalSlot): static
    {
        if ($this->evalSlots->removeElement($evalSlot)) {
            if ($evalSlot->getUserId() === $this) {
                $evalSlot->setUserId(null);
            }
        }

        return $this;
    }

    public function getNotifications(): ?array
    {
        return $this->notifications;
    }

    public function setNotifications(array $notifications): static
    {
        $this->notifications = $notifications;
        return $this;
    }

    public function addNotification(string $message, ?string $link = null): static
    {
        $this->notifications[] = [
            'message' => $message,
            'link' => $link,
            'timestamp' => (new \DateTime())->format('Y-m-d H:i:s')
        ];
        $this->unreadNotificationsCount++;

        return $this;
    }

    public function removeNotification(int $index): static
    {
        if (isset($this->notifications[$index]))
        {
            unset($this->notifications[$index]);
            $this->notifications = array_values($this->notifications);
            $this->unreadNotificationsCount = max(0, $this->unreadNotificationsCount - 1);
        }
        return $this;
    }

    public function getUnreadNotificationsCount(): int
    {
        return $this->unreadNotificationsCount;
    }

    public function setUnreadNotificationsCount(int $count): static
    {
        $this->unreadNotificationsCount = $count;
        return $this;
    }

    public function getLevel(): int
    {
        return $this->level;
    }

    public function setLevel(int $level): static
    {
        $this->level = $level;
        return $this;
    }
}

Rush 01/intranet/templates/components/navbar.html.twig
<div class="navbar">
    <ul>
        <li>
            {% if app.user %}
                <a class="navbar-logo" href="{{ path('userpage', {'id': app.user.id}) }}">
            {% else %}
                <a class="navbar-logo" href="{{ path('homepage') }}">
            {% endif %}
                <svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 137.6 96.6" fill="#fff" stroke="transparent" width="40" height="32" style="margin-left: 2px;">
                    <path d="M229.2 443.9h50.7v25.4h25.3v-45.9h-50.6l50.6-50.7h-25.3l-50.7 50.7zM316.1 398.1l25.3-25.4h-25.3z" fill="#fff" transform="translate(-229.2 -372.7)" style="margin-left: 2px;">
                    </path>
                    <path d="m341.4 398.1-25.3 25.3v25.3h25.3v-25.3l25.4-25.3v-25.4h-25.4zM366.8 423.4l-25.4 25.3h25.4z" fill="#fff" transform="translate(-229.2 -372.7)" style="margin-left: 2px;">
                    </path>
                </svg>
            </a>
        </li>
        <li>
            {% if app.user %}
                <a href="{{ path('userpage', {'id': app.user.id}) }}">
            {% else %}
                <a href="{{ path('login') }}">
            {% endif %}
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="#fff">
                <path fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" d="M23.5 23.5a10.135 10.135 0 0 0-1-4.057c-.746-1.492-4-2.5-8-4v-3a3.75 3.75 0 0 0 1.5-3c.5 0 1-2 0-2.5 0-.3 1.339-2.8 1-4.5-.5-2.5-7.5-2.5-8-.5-3 0-1 4.594-1 5-1 .5-.5 2.5 0 2.5a3.75 3.75 0 0 0 1.5 3v3c-4 1.5-7.255 2.508-8 4a10.135 10.135 0 0 0-1 4.057Z">
                </path>
            </svg>
            </a>
        </li>
        <li>
            <a href="{{ path('project_list') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="#fff">
                    <path fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" d="M9.499 10.499a4 4 0 1 0 8 0 4 4 0 1 0-8 0ZM.5 5.499a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0ZM20.5 1.999a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0ZM.5 21.999a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0ZM11.999 21.999a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0ZM3.06 20.938l7.62-7.601M16.333 7.676l4.605-4.616M3.35 6.149l6.472 2.775M20.562 14.028l-3.618-1.495M13.499 20.499v-6M20.5 14.499a1.5 1.5 0 1 0 3 0 1.5 1.5 0 1 0-3 0Z">
                    </path>
                </svg>
            </a>
        </li>
        <li>
            <a href="{{ path('chat_index') }}">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="#fff">
                    <path fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" d="M9.5 16.5c0 4.288 5 7.5 9.5 5.5l4 1.5-1.5-3a4.994 4.994 0 0 0 2-4c0-3.154-3.134-6-7-6s-7 2.846-7 6Z">
                    </path>
                    <path fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" d="M17.4 8.5a5.822 5.822 0 0 0 .1-1c0-3.866-3.8-7-8.5-7S.5 3.634.5 7.5a6.434 6.434 0 0 0 2.517 4.97L1 16l4.939-1.976a9.993 9.993 0 0 0 1.561.361">
                    </path>
                </svg>
            </a>
        </li>
        <li>
            <a href="{{ path('shop_index') }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="none" stroke="#fff" viewBox="0 0 24 24">
                <path stroke="#fff" stroke-linecap="round" stroke-linejoin="round" d="M6 2l1.5 2H20a1 1 0 0 1 .98 1.2l-1.6 8A2 2 0 0 1 17.42 15H8.58a2 2 0 0 1-1.96-1.8L4 4H2" />
                <circle cx="9" cy="20" r="1" fill="#fff"/>
                <circle cx="17" cy="20" r="1" fill="#fff"/>
                </svg>
        </a>
        </li>

    </ul>
</div>

Rush 01/intranet/templates/components/script.html.twig
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const input = document.getElementById('user-search');
        const resultsContainer = document.getElementById('search-results');

        if (!input || !resultsContainer) {
            return; // Elementi non trovati, esci silenziosamente
        }

        input.addEventListener('input', async function () {
            const query = input.value.trim();

            if (query.length === 0) {
                resultsContainer.style.display = 'none';
                resultsContainer.innerHTML = '';
                return;
            }

            try {
                const response = await fetch(`/api/search/users?q=${encodeURIComponent(query)}`);
                const users = await response.json();

                resultsContainer.innerHTML = '';
                if (users.length > 0) {
                    users.forEach(user => {
                        const li = document.createElement('li');
                        const link = document.createElement('a');
                        link.href = `/userpage/${user.id}`;
                        link.textContent = `${user.firstName} ${user.lastName} (${user.email})`;
                        li.appendChild(link);
                        resultsContainer.appendChild(li);
                    });
                    resultsContainer.style.display = 'block';
                } else {
                    resultsContainer.style.display = 'none';
                }
            } catch (error) {
                console.error('Error fetching users:', error);
            }
        });

        document.addEventListener('click', function (e) {
            if (!input.contains(e.target) && !resultsContainer.contains(e.target)) {
                resultsContainer.style.display = 'none';
            }
        });
    });
</script>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const toggle = document.getElementById('dropdown-toggle');
    const menu = document.getElementById('dropdown-menu');

    if (!toggle || !menu) {
        return; // Elementi non trovati, esci silenziosamente
    }

    toggle.addEventListener('click', function (e) {
        e.stopPropagation();
        menu.style.display = (menu.style.display === 'block') ? 'none' : 'block';
    });

    document.addEventListener('click', function () {
        menu.style.display = 'none';
    });
});
</script>

<script src="{{ asset('js/notifications.js') }}"></script>

Rush 01/intranet/templates/components/searchbar.html.twig
<div class="header">

    <div class="search-container">

        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="21">
            <path fill="none" stroke="#000" stroke-linecap="round" stroke-linejoin="round" d="M.5 10.5a10 10 0 1 0 20 0 10 10 0 1 0-20 0ZM23.5 23.5l-5.929-5.929">
            </path>
        </svg>

        <input class="sbar" type="text" id="user-search" name="search" placeholder="Search users..." autocomplete="off">
        <ul id="search-results" class="search-results"></ul>

    </div>

    <div class="notifications-container">
        <button id="notifications-btn" class="notifications-btn">
            🔔
            <span id="notifications-count" class="notifications-count">0</span>
        </button>
        <div id="notifications-dropdown" class="notifications-dropdown" style="display: none;">
            <div class="notifications-header">
                <h4>Notifications</h4>
                <a href="/notifications" class="view-all-notifications-btn">See all notifications</a>
            </div>
            <div id="notifications-list" class="notifications-list">
                <p class="no-notifications">No notifications</p>
            </div>
        </div>
    </div>

    <div class="dropdown" id="dropdown-toggle" style="cursor: pointer;">

        <p>{{ originalUser.email }}</p>

        <img class="round-img"
            src="{{ originalUser.image is not empty ? originalUser.image : asset('images/default_profile.jpeg') }}"
            alt="Profile Image"
            style="max-width:150px;">

        <div class="user-dropdown" id="dropdown-menu">
            <ul>
                <li>
                    <a href="/profile/edit">Edit</a>
                </li>
                {% if user.role is defined and user.role and user.role.value == 'admin' %}
                    <li>
                        <a href="/admin">Admin</a>
                    </li>
                {% else %}
                    <li>
                        <a href="/userpage/{{ user.id }}">User Page</a>
                    </li>
                {% endif %}
                <li>
                    <a href="{{ path('app_logout') }}">Logout</a>
                </li>
            </ul>
        </div>
    </div>

</div>

Rush 01/intranet/templates/components/userinfo.html.twig
<div class="user_info">

    <img src="{{ user.image is not empty ? user.image : asset('images/default_profile.jpeg') }}"
          alt="Profile Image"
          style="max-width:150px;">

    <div class="pick_and_name">

        <h2 class="user_name">
            {{ user.getFirstName() }}
            {{ user.getLastName() }}
        </h2>

        <div class="levelBar">
            <p>Level {{ user.level }} — {{ user.experience }} XP / {{ xpGoal }} XP</p>

            <div class="xp-bar">
                <div class="xp-fill" style="width: {{ xpProgress }}%;"></div>
            </div>
        </div>
    
    </div>

    <div class="info">
        <ul>
        <li>Email: {{ user.getEmail() }}</li>
        <li>Ev. P: {{ user.getEvalPoints() }}</li>
        </ul>
    </div>

</div>